### ISSUE TITLE
dash doesn't compile with gcc 8.2 anymore

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#579]
gcc: 8.2.0
openmpi: 3.1.1

test and examples on

dash_dev/dash/include/dash/algorithm/Operation.h:76:8: error: too many template-parameter-lists
 struct dart_reduce_operation<BinaryOperation,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         typename std::enable_if<
         ~~~~~~~~~~~~~~~~~~~~~~~~
           // no-ops cannot be used in DART collectives
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           BinaryOperation::op_kind() != dash::internal::OpKind::NOOP &&
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           // only pre-defined operations can be used in DART collectives,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           // they are derived from dash::internal::ReduceOperation
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           std::is_base_of<
           ~~~~~~~~~~~~~~~~
             dash::internal::ReduceOperation<
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               typename BinaryOperation::value_type,
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               BinaryOperation::dart_operation(),
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               BinaryOperation::op_kind(), true>,
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             BinaryOperation>::value>::type>
