### ISSUE TITLE
Enable all available compiler warnings

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#231]
We currently compile with warning flags `-Wall -Wpedantic -Wextra` which is basically reasonable, however g++ offers several additional warning options that are not enabled with this configuration.

**Comment by rkowalewski** [comment]
Which one for example do you mean?

EDIT: Got it. I assume you refer to Pull request #232

**Comment by devreal** [comment]
Thanks for the additional flags. While this is only a developer option, it greatly helps to have a clean build again soon. Otherwise, more critical warnings might go unnoticed. I will start fixing the DART part soon.

**Comment by fuchsto** [comment]
@devreal Thank you, but don't give it high priority.

**Comment by devreal** [comment]
[UPDATE] Submitted comment before finished writing, classical slipped-off-my-mouse mistake ^^ [/UPDATE]

Just out of curiosity, I ran a make and looked at the new warnings. Some seem to be pure style-related, e.g.,
```
dart_team_private.c:79:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 int dart_adapt_teamlist_destroy ()
```
Here, a `void` is missing in the parentheses. 

Others are really strange, e.g., 

```
/home/joseph/src/dash/dash/dart-impl/base/src/locality.c: In function ‘dart__base__locality__group_subdomains’:
/home/joseph/src/dash/dash/dart-impl/base/src/locality.c:954:3: warning: assuming signed overflow does not occur when simplifying conditional [-Wstrict-overflow]
   for (int g = 0; g < num_existing_domain_groups; g++) {
   ^
```

This seems to be some strange behavior of GCC, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55217

Only the warnings introduced with `-Wdiscarded-qualifiers` seem to be useful at this point:
```
/home/joseph/src/dash/dash/dart-impl/base/src/internal/domain_locality.c: In function ‘dart__base__locality__domain__parent’:
/home/joseph/src/dash/dash/dart-impl/base/src/internal/domain_locality.c:328:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     *domain_out = (const dart_domain_locality_t *)(domain_in);
```

**Comment by fuchsto** [comment]
That was unintended, the style-related warnings should be disabled.

**Comment by devreal** [comment]
Addendum: `-Wmissing-prototypes` seems to be useful as well (spots functions that could be marked `static`), e.g., 

```
host_topology.c:145:12: warning: no previous prototype for ‘dart__base__host_topology__update_module_locations’ [-Wmissing-prototypes]
 dart_ret_t dart__base__host_topology__update_module_locations(
```

**Comment by devreal** [comment]
Here is a nice gem: GCC 5.4.1 crashes on `dart-impl/mpi/src/dart_segment.c` with `-Wstrict-overflow=5`:

```
In function ‘hash_segid’:
in pp_format, at pretty-print.c:614
   return (abs(segid) % DART_SEGMENT_HASH_SIZE);
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
``` 
I installed GCC 6 which has this bug fixed:
```
src/dash/dash/dart-impl/mpi/src/dart_segment.c: In function ‘hash_segid’:
/home/joseph/src/dash/dash/dart-impl/mpi/src/dart_segment.c:64:3: warning: assuming signed overflow does not occur when determining that expression is always non-negative [-Wstrict-overflow]
   return (abs(segid) % DART_SEGMENT_HASH_SIZE);
```
I still cannot make any sense of this warning, see my comment above. Unless someone has a good explanation and a fix for the warning we might want to consider removing this flag...

**Comment by devreal** [comment]
> That was unintended, the style-related warnings should be disabled.

I suggest removing the flags `-Wold-style-definition` and `-Wstrict-prototypes` since they are mainly style-related.

However, I was surprised that warnings of unused variables and functions are explicitly disabled through `-Wno-unused`. I strongly suggest to enable these warnings since they can help detect broken code or at least help clean up code.

**Comment by fuchsto** [comment]
The reason to configure `-Wno-unused` is that

1. it reports temporaries used for logging in most cases
2. compilers are really good at eliminating unused temporaries (given they are results from a const / constexpr which is usually the case)

Not implying that these are good reasons, though. I deactivated this warning category after I studied compiler warnings of biblical dimension without finding an actual defect.

I agree that these should be re-anabled in development configuration.

**Comment by fuchsto** [comment]
`-Wstrict-overflow` is rather important to us because it adds checks on additional stages in the optimization of literal expressions, in particular like those in DASH index set arithmetics.

So, for example:

```c++
if (x + 1 <= x)  // <-- could overflow
// ... but will be reduced to:
if (false)
// ... and therefore not checked for overflow unless `Wstrict-overflow` is used
```
With `-Wstrict-overflow=k`, the level `k` determines the degree of "reduced common sense" of these warnings. `k=5` is really too excessive, as illustrated in the `abs(...) % X` example. Usually 3 or 4 are plenty.

**Comment by devreal** [comment]
OK, I understand your point on `-Wstrict-overflow` and we should lower the level to something more sensible. However, even with level 3 I see warnings that I cannot make any sense of. Maybe you know a way to adapt the code to fix avoid the warning. Otherwise, this is really dangerous it leads to situations where other warnings are overseen or even intentionally ignored (because hey, we ignore the overflow warnings as well, right?). If this is only relevant in a few places, we might want to make it a separate flag that you can enable while working on these places.

On the topic of unused variables/functions: I agree that the compiler is often able to optimize out unused variables. However, if function calls are involved with unused variables, this might not be possible as the compiler does not know about possible side-effects. This is a potential performance hit. It also helps spotting misspelled symbol names, so it's definitely helpful. 

I resurrected `feat-231-ccwarn` and will add my changes for discussion.

**Comment by devreal** [comment]
One more note on `-Wstrict-overflow`: With level 3, we receive warnings from within MPI as well:

```
In file included from /usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h:291:0,
                 from /usr/lib/openmpi/include/mpi.h:2673,
                 from /usr/include/hdf5/openmpi/H5public.h:61,
                 from /usr/include/hdf5/openmpi/hdf5.h:24,
                 from /home/joseph/src/dash/dash/dash/include/dash/io/hdf5/StorageDriver.h:15,
                 from /home/joseph/src/dash/dash/dash/include/dash/io/HDF5.h:4,
                 from /home/joseph/src/dash/dash/dash/include/libdash.h:58,
                 from /home/joseph/src/dash/dash/dash/examples/bench.08.transform/main.cpp:1:
/usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h: In member function ‘virtual void MPI::Comm::Alltoallw(const void*, const int*, const int*, const MPI::Datatype*, void*, const int*, const int*, const MPI::Datatype*) const’:
/usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h:414:1: warning: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Wstrict-overflow]
 MPI::Comm::Alltoallw(const void *sendbuf, const int sendcounts[],
```

I do not think we should have this flag enabled for all developers as it needlessy clutters compiler output and makes spotting more severe warnings problematic. We can put it as a separate CMake flag though if these diagnostics are important in some places...

**Comment by fuchsto** [comment]
Ah well, that makes this flag unusable for us then. Thanks for your changes!

**Comment by devreal** [comment]
I fixed an issue that prevented builds with Clang from succeeding. The Intel compiler also complains about some warning flags he does not understand, in particular:

```
icc: command line warning #10006: ignoring unknown option '-Wcast-align'
icc: command line warning #10006: ignoring unknown option '-Wopenmp-simd'
icc: command line warning #10006: ignoring unknown option '-Wstrict-overflow=3'
icc: command line warning #10006: ignoring unknown option '-Wbad-function-cast'
icc: command line warning #10006: ignoring unknown option '-Wc99-c11-compat'
icc: command line warning #10006: ignoring unknown option '-Wnested-externs'
icc: command line warning #10006: ignoring unknown option '-Wmissing-parameter-type'
```

I will add a fix to #234

**Comment by fuchsto** [comment]
Hm! icc-14 is fine with it on my machine. What version of icc did you use?

**Comment by devreal** [comment]
I tested with icc 2016. It's likely that these warnings have been removed again, Intel does not seem to too transparent about that. We can add `-diag-disable=10006` to suppress the warning about unsupported warnings ^^

**Comment by devreal** [comment]
ICC 2016 has the following interesting warning, that we might want to fix:

```
In file included from /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/include/dash/Exception.h(6),
                 from /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/include/dash/Distribution.h(5),
                 from /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/src/Distribution.cc(2):
/zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/include/dash/exception/OutOfRange.h(13): warning #2304: non-explicit constructor with single argument may cause implicit type conversion
    OutOfRange(const ::std::string & msg)
```

However, there is a more serious issue here: The build fails with the following error:

```
In file included from /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/src/Distribution.cc(1):
/zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/include/dash/Types.h(186): error: expression must have a constant value
  constexpr global_unit_t UNDEFINED_GLOBAL_UNIT_ID{DART_UNDEFINED_UNIT_ID};
```

I'm still not sure why this fails with Intel while the build succeeds with Clang and GCC.

UPDATE: There was an earlier error that I did not see immediately (hidden in many warnings ^^):

```
In file included from /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/include/dash/Types.h(7),
                 from /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/src/Distribution.cc(1):
/zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/include/dash/internal/Unit.h(52): error: expected a ";"
    constexpr explicit unit_id() noexcept
```

**Comment by fuchsto** [comment]
Narf?
Is that already fixed in your PR, or should I hotfix this?

**Comment by devreal** [comment]
I haven't managed to fix it because I'm not sure what exactly causes the error. Using a small test case, I can reproduce the problem with ICC 16.0.3 (which claims to fully support C++11 `noexcept`). The example builds fine with 17.0.0. I suspect that this is a compiler bug. I will ask for a OpenMPI installation built with 17.0.0 to validate it against DASH.

Let me know if you have a hot fix :) We could introduce a macro `NOEXCEPT` that evaluates to empty for ICC <17.0.0...

**Comment by devreal** [comment]
I have to revert my previous statement on the build error: the problem was that the Intel compiler module on our cluster did not load a newer GCC version, which is required by the Intel compiler to properly compiler C++11 features. When I bring the GCC 6.2.0 into the game everything works fine. 

I am about to commit some more fixes to warnings though.

**Comment by fuchsto** [comment]
Hm! We want to be compatible to gcc-4.9, though. I will heat up my build-VM and rerun all configs to be sure.
